### ISSUE TITLE
[BUG] CoverManager overwrites the image with txt extension. Renaming aparently fixes

### ISSUE THREAD

**Issue by ThePromidius** [ThePromidius/Manga-Manager#87]
```Platypusq — hoy a las 17:32
So I've just started trying to use this for editing covers, but I'm running into an issue where sometimes when I select "Replace Current Cover" it will instead not delete the current cover, and save the new cover as a txt file instead of an image file.  Just changing the extension to .jpg makes the image work properly. I was curious if anyone else had run into this issue?
Promidius — hoy a las 17:44
Huh thats really weird
Platypusq — hoy a las 17:46
When using the delete cover tool it does something similar, in that it just doesn't delete the old cover.  The log says that it is backing up and deleting the cover, but then it just adds in back in.  Does the log say that it is deleting the cover even if it doesn't find any?
Promidius — hoy a las 17:46
send the log and i'll be able to answer
Promidius — hoy a las 17:47
lol i think i just found the issue
Platypusq — hoy a las 17:48
Oh, that was fast lol
Promidius — hoy a las 17:52
can you send me the content of that zip?
like the filenames inside of it 
Platypusq — hoy a las 17:53
The files are in this log, but this is everything I did, not just the ones that didn't work https://pastebin.com/ZSWFAufc.
For a zip that definitely didn't work: 
Atsumare! Fushigi Kenkyu-bu_0.jpg
Atsumare! Fushigi Kenkyu-bu_1.jpg
Atsumare! Fushigi Kenkyu-bu_2.jpg
Atsumare! Fushigi Kenkyu-bu_3.jpg
Atsumare! Fushigi Kenkyu-bu_4.jpg
Atsumare! Fushigi Kenkyu-bu_5.jpg
Atsumare! Fushigi Kenkyu-bu_6.jpg
Atsumare! Fushigi Kenkyu-bu_7.jpg
Atsumare! Fushigi Kenkyu-bu_8.jpg 
Promidius — hoy a las 17:59
i'll get back to you when i have this fixed. Thanks for the report
```

**Comment by kou9221** [comment]
Cover Manager overwriting doesn't seem to work. I've try it on my multiple cbz file it doesn't replace the first page of cbz. Nothing happens when doing the process.

**Comment by ThePromidius** [comment]
Are you on stable? this was fixed on develop version. I'm going to release monthly update soon

**Comment by kou9221** [comment]
> can you tell me the content (name of files) of one of those cbz?

Do you mean the filename of those cbz or the filename of images inside the cbz?

**Comment by ThePromidius** [comment]
> > can you tell me the content (name of files) of one of those cbz?
> 
> Do you mean the filename of those cbz or the filename of images inside the cbz?

The filename of the images inside the cbz just to make sure. But as mentioned earlier it's probably fixed

**Comment by kou9221** [comment]
> > > can you tell me the content (name of files) of one of those cbz?
> > 
> > 
> > Do you mean the filename of those cbz or the filename of images inside the cbz?
> 
> The filename of the images inside the cbz just to make sure. But as mentioned earlier it's probably fixed

Here:

![Window-2022-08-16 21_39_19](https://user-images.githubusercontent.com/98811570/184895791-96deaf27-49a0-488d-9b48-c825fa50a199.png)

**Comment by ThePromidius** [comment]
Yeah... That looks fine. As i mentioned earlier its fixed in develop.
